import 'package:insta_modern/Providers/posts.dart';

const STORY_LINE = [
  ["assets/images/profs/prof1.jpg", "alice"],
  ["assets/images/profs/prof2.jpg", "mike_vendor"],
  ["assets/images/profs/prof3.jpg", "sonia_blake"],
  ["assets/images/profs/prof4.jpg", "joerge21"],
  ["assets/images/profs/prof5.jpg", "chris._."],
  ["assets/images/profs/prof6.jpg", "singmu__"],
];

final POSTS = [
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: [
      "assets/images/posts/post1.jpg",
      "assets/images/posts/post4.jpg",
      "assets/images/posts/post6.jpg",
    ],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "1",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg", "assets/images/posts/post7.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "2",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg", "assets/images/posts/post8.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "3",
  ),
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "4",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "5",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "6",
  ),
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "7",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "8",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "9",
  ),
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "10",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "11",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "12",
  ),
  //
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "13",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "14",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "15",
  ),
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "16",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "17",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "18",
  ),

  //
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "18",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "19",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "20",
  ),
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "21",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "22",
  ),
  Post(
    authorUserName: "mike_vendor",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post3.jpg", "assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof2.jpg",
    id: "23",
  ),
];

const HIGHLIGHTS = [
  ["assets/images/highlights/h1.jpg", "Business"],
  ["assets/images/highlights/h2.jpg", "Photography"],
  ["assets/images/highlights/h3.jpg", "Life Style"],
  ["assets/images/highlights/h4.jpg", "dog"],
  ["assets/images/highlights/h5.jpg", "Vacation"],
  ["assets/images/highlights/h6.jpg", "sport"]
];

final ACTIVITIES = [
  Post(
    authorUserName: "sonia_blake",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof3.jpg",
    id: "1",
  ),
  Post(
    authorUserName: "chris._.",
    likesCount: 148,
    commentsCount: 54,
    medias: ["assets/images/posts/post2.jpg", "assets/images/posts/post1.jpg"],
    authorProfileImageURL: "assets/images/profs/prof5.jpg",
    id: "2",
  ),
];
